spring:
  application:
    name: traffic-light-hackaton
  ai:
    openai:
      api-key: ${SPRING_OPENAI_API_KEY}

chat:
  context:
    text: classpath:static/context/chatContextText.txt

ml:
  python:
    service:
      url: ${ML_PYTHON_SERVICE_URL:http://16.171.62.159:5000}
